In [1]:
import torch

print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

True
12.4
NVIDIA GeForce RTX 3050 6GB Laptop GPU

In [2]:
import pandas as pd
import glob

files = glob.glob("*.csv")

first_file = True

for file in files:
    print("Processing:", file)

    for chunk in pd.read_csv(file, chunksize=100000):
        sample_chunk = chunk.sample(frac=0.05, random_state=42)

        sample_chunk.to_csv(
            "combined_5percent_data.csv",
            mode="w" if first_file else "a",
            index=False,
            header=first_file
        )

        first_file = False

print("Combined CSV created!")

Processing: Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
Processing: Friday-16-02-2018_TrafficForML_CICFlowMeter.csv

C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):

Processing: Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Processing: Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv

C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):

Processing: Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Processing: Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
Processing: Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
Processing: Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Processing: Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):

Combined CSV created!

C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\57164018.py:11: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file, chunksize=100000):

In [3]:
df = pd.read_csv("combined_5percent_data.csv")

C:\Users\Aditya\AppData\Local\Temp\ipykernel_19948\3729086213.py:1: DtypeWarning: Columns (0: Dst Port, 1: Protocol, 2: Flow Duration, 3: Tot Fwd Pkts, 4: Tot Bwd Pkts, 5: TotLen Fwd Pkts, 6: TotLen Bwd Pkts, 7: Fwd Pkt Len Max, 8: Fwd Pkt Len Min, 9: Fwd Pkt Len Mean, 10: Fwd Pkt Len Std, 11: Bwd Pkt Len Max, 12: Bwd Pkt Len Min, 13: Bwd Pkt Len Mean, 14: Bwd Pkt Len Std, 15: Flow Byts/s, 16: Flow Pkts/s, 17: Flow IAT Mean, 18: Flow IAT Std, 19: Flow IAT Max, 20: Flow IAT Min, 21: Fwd IAT Tot, 22: Fwd IAT Mean, 23: Fwd IAT Std, 24: Fwd IAT Max, 25: Fwd IAT Min, 26: Bwd IAT Tot, 27: Bwd IAT Mean, 28: Bwd IAT Std, 29: Bwd IAT Max, 30: Bwd IAT Min, 31: Fwd PSH Flags, 32: Bwd PSH Flags, 33: Fwd URG Flags, 34: Bwd URG Flags, 35: Fwd Header Len, 36: Bwd Header Len, 37: Fwd Pkts/s, 38: Bwd Pkts/s, 39: Pkt Len Min, 40: Pkt Len Max, 41: Pkt Len Mean, 42: Pkt Len Std, 43: Pkt Len Var, 44: FIN Flag Cnt, 45: SYN Flag Cnt, 46: RST Flag Cnt, 47: PSH Flag Cnt, 48: ACK Flag Cnt, 49: URG Flag Cnt, 50: CWE Flag Count, 51: ECE Flag Cnt, 52: Down/Up Ratio, 53: Pkt Size Avg, 54: Fwd Seg Size Avg, 55: Bwd Seg Size Avg, 56: Fwd Byts/b Avg, 57: Fwd Pkts/b Avg, 58: Fwd Blk Rate Avg, 59: Bwd Byts/b Avg, 60: Bwd Pkts/b Avg, 61: Bwd Blk Rate Avg, 62: Subflow Fwd Pkts, 63: Subflow Fwd Byts, 64: Subflow Bwd Pkts, 65: Subflow Bwd Byts, 66: Init Fwd Win Byts, 67: Init Bwd Win Byts, 68: Fwd Act Data Pkts, 69: Fwd Seg Size Min, 70: Active Mean, 71: Active Std, 72: Active Max, 73: Active Min, 74: Idle Mean, 75: Idle Std, 76: Idle Max, 77: Idle Min) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("combined_5percent_data.csv")

In [4]:
df

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,8080,6,02/03/2018 02:00:17,505,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
1,8080,6,02/03/2018 02:56:09,11806,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
2,8080,6,02/03/2018 01:34:34,442,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
3,8080,6,02/03/2018 02:16:18,10948,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
4,8080,6,02/03/2018 10:46:51,10246,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414209,9081,6,28/02/2018 02:23:17,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
414210,53,17,28/02/2018 03:37:08,869,1,1,41,57,41,41,...,8,0.0,0.0,0,0,0.0,0.0,0,0,Benign
414211,53,17,28/02/2018 08:30:41,1175,1,1,34,90,34,34,...,8,0.0,0.0,0,0,0.0,0.0,0,0,Benign
414212,3389,6,28/02/2018 02:40:14,1679517,8,7,1128,1581,661,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
414213,8085,6,28/02/2018 02:23:17,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration

In [5]:
df.columns = df.columns.str.strip()

In [9]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
# 2. Remove duplicate columns
df = df.loc[:, ~df.columns.duplicated()]

# 3. Remove timestamp/date columns
for col in df.columns:
    if "time" in col.lower() or "timestamp" in col.lower():
        df.drop(columns=[col], inplace=True)

# 4. Remove known duplicate CICIDS column if present
if "Fwd Header Length.1" in df.columns:
    df.drop(columns=["Fwd Header Length.1"], inplace=True)

# 5. Set target column
target_col = "Label"

# 6. Remove rows where label is missing
df = df[df[target_col].notna()]

# 7. Clean label values
df[target_col] = df[target_col].astype(str).str.strip()

# 8. Remove accidental repeated header rows
df = df[df[target_col].str.lower() != "label"]

# 9. Keep only required classes
selected_classes = ["Benign", "Bot", "Infilteration"]
df = df[df[target_col].isin(selected_classes)]

# 10. Replace infinity values
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# 11. Convert feature columns to numeric
for col in df.columns:
    if col != target_col:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# 12. Remove null values
df.dropna(inplace=True)

# 13. Remove duplicate rows
df.drop_duplicates(inplace=True)

# 14. Encode labels
label_encoder = LabelEncoder()
df["Encoded_Label"] = label_encoder.fit_transform(df[target_col])

# 15. Separate features and target
X = df.drop(columns=[target_col, "Encoded_Label"])
y = df["Encoded_Label"]

# 16. Keep only numeric features
X = X.select_dtypes(include=[np.number])

# 17. Remove low-information sparse rows
non_zero_mask = (X != 0).sum(axis=1) > 5
X = X[non_zero_mask]
y = y[non_zero_mask]

# 18. Final cleaned dataframe
df_cleaned = X.copy()
df_cleaned["Encoded_Label"] = y.values

# Final checks
print("Final Shape:", df_cleaned.shape)
print("\nClass Encoding:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nClass Distribution:")
print(df_cleaned["Encoded_Label"].value_counts())

print("\nNull Values:", df_cleaned.isnull().sum().sum())
print("Infinity Values:", np.isinf(df_cleaned.select_dtypes(include=[np.number])).sum().sum())
print("Duplicate Rows:", df_cleaned.duplicated().sum())

Final Shape: (298989, 79)

Class Encoding:
{'Benign': np.int64(0), 'Bot': np.int64(1), 'Infilteration': np.int64(2)}

Class Distribution:
Encoded_Label
0    283315
1      7871
2      7803
Name: count, dtype: int64

Null Values: 0
Infinity Values: 0
Duplicate Rows: 0

In [13]:
import pandas as pd
import glob

files = glob.glob("*.csv")

all_samples = []

for file in files:
    print("\nProcessing:", file)

    df_temp = pd.read_csv(file, low_memory=False)
    df_temp.columns = df_temp.columns.str.strip()

    label_cols = [col for col in df_temp.columns if col.strip().lower() == "label"]

    if len(label_cols) == 0:
        print("Skipping: No Label column")
        continue

    label_col = label_cols[0]
    df_temp = df_temp.rename(columns={label_col: "Label"})

    df_temp["Label"] = df_temp["Label"].astype(str).str.strip()
    df_temp = df_temp[df_temp["Label"].str.lower() != "label"]

    print("Original shape:", df_temp.shape)
    print(df_temp["Label"].value_counts())

    sampled_groups = []

    for label, group in df_temp.groupby("Label"):
        n = max(1, int(len(group) * 0.05))
        sampled = group.sample(n=n, random_state=42)
        sampled_groups.append(sampled)

    df_sample = pd.concat(sampled_groups, ignore_index=True)

    print("Sampled shape:", df_sample.shape)
    print(df_sample["Label"].value_counts())

    all_samples.append(df_sample)

final_df = pd.concat(all_samples, ignore_index=True)

print("\nFinal sampled shape:", final_df.shape)
print("\nFinal label distribution:")
print(final_df["Label"].value_counts())

final_df.to_csv("all_csv_5_percent_all_attacks.csv", index=False)

Processing: combined_5percent_data.csv
Original shape: (414211, 80)
Label
Benign                      305596
DDOS attack-HOIC             34350
DoS attacks-Hulk             23059
Bot                          14283
FTP-BruteForce                9695
SSH-Bruteforce                9368
Infilteration                 8015
DoS attacks-SlowHTTPTest      7028
DoS attacks-GoldenEye         2106
DoS attacks-Slowloris          568
DDOS attack-LOIC-UDP            91
Brute Force -Web                32
Brute Force -XSS                14
SQL Injection                    6
Name: count, dtype: int64
Sampled shape: (20705, 80)
Label
Benign                      15279
DDOS attack-HOIC             1717
DoS attacks-Hulk             1152
Bot                           714
FTP-BruteForce                484
SSH-Bruteforce                468
Infilteration                 400
DoS attacks-SlowHTTPTest      351
DoS attacks-GoldenEye         105
DoS attacks-Slowloris          28
DDOS attack-LOIC-UDP            4
Brute Force -Web                1
Brute Force -XSS                1
SQL Injection                   1
Name: count, dtype: int64

Processing: Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
Benign    762384
Bot       286191
Name: count, dtype: int64
Sampled shape: (52428, 80)
Label
Benign    38119
Bot       14309
Name: count, dtype: int64

Processing: Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048574, 80)
Label
DoS attacks-Hulk            461912
Benign                      446772
DoS attacks-SlowHTTPTest    139890
Name: count, dtype: int64
Sampled shape: (52427, 80)
Label
DoS attacks-Hulk            23095
Benign                      22338
DoS attacks-SlowHTTPTest     6994
Name: count, dtype: int64

Processing: Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
Benign              1048009
Brute Force -Web        362
Brute Force -XSS        151
SQL Injection            53
Name: count, dtype: int64
Sampled shape: (52427, 80)
Label
Benign              52400
Brute Force -Web       18
Brute Force -XSS        7
SQL Injection           2
Name: count, dtype: int64

Processing: Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
Original shape: (331100, 80)
Label
Benign           238037
Infilteration     93063
Name: count, dtype: int64
Sampled shape: (16554, 80)
Label
Benign           11901
Infilteration     4653
Name: count, dtype: int64

Processing: Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
Benign                   996077
DoS attacks-GoldenEye     41508
DoS attacks-Slowloris     10990
Name: count, dtype: int64
Sampled shape: (52427, 80)
Label
Benign                   49803
DoS attacks-GoldenEye     2075
DoS attacks-Slowloris      549
Name: count, dtype: int64

Processing: Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
Benign              1048213
Brute Force -Web        249
Brute Force -XSS         79
SQL Injection            34
Name: count, dtype: int64
Sampled shape: (52426, 80)
Label
Benign              52410
Brute Force -Web       12
Brute Force -XSS        3
SQL Injection           1
Name: count, dtype: int64

Processing: Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
Benign            667626
FTP-BruteForce    193360
SSH-Bruteforce    187589
Name: count, dtype: int64
Sampled shape: (52428, 80)
Label
Benign            33381
FTP-BruteForce     9668
SSH-Bruteforce     9379
Name: count, dtype: int64

Processing: Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (1048575, 80)
Label
DDOS attack-HOIC        686012
Benign                  360833
DDOS attack-LOIC-UDP      1730
Name: count, dtype: int64
Sampled shape: (52427, 80)
Label
DDOS attack-HOIC        34300
Benign                  18041
DDOS attack-LOIC-UDP       86
Name: count, dtype: int64

Processing: Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv
Original shape: (613071, 80)
Label
Benign           544200
Infilteration     68871
Name: count, dtype: int64
Sampled shape: (30653, 80)
Label
Benign           27210
Infilteration     3443
Name: count, dtype: int64

Final sampled shape: (434902, 80)

Final label distribution:
Label
Benign                      320882
DDOS attack-HOIC             36017
DoS attacks-Hulk             24247
Bot                          15023
FTP-BruteForce               10152
SSH-Bruteforce                9847
Infilteration                 8496
DoS attacks-SlowHTTPTest      7345
DoS attacks-GoldenEye         2180
DoS attacks-Slowloris          577
DDOS attack-LOIC-UDP            90
Brute Force -Web                31
Brute Force -XSS                11
SQL Injection                    4
Name: count, dtype: int64

In [14]:
df = pd.read_csv("all_csv_5_percent_all_attacks.csv")

In [15]:
df

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,53191,6,15/02/2018 05:43:16,4,3,0,31,0.0,31,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Benign
1,80,6,22/02/2018 03:19:30,54907473,2,0,0,0.0,0,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Benign
2,53,17,02/03/2018 11:40:31,1595,1,1,42,102.0,42,42,...,8,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Benign
3,3389,6,15/02/2018 10:21:21,5056732,9,8,1128,1581.0,661,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Benign
4,50542,6,01/03/2018 10:00:09,19,1,1,0,0.0,0,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434897,443,6,28/02/2018 02:02:21,116115617,21,25,648,3028.0,342,0,...,20,23491.0,41128.55105,154090.0,11467.0,9652809.333,1202962.156,10000000.0,5833074.0,Infilteration
434898,52986,6,28/02/2018 11:21:42,34,1,1,0,0.0,0,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Infilteration
434899,443,6,28/02/2018 11:14:43,73338,5,5,675,219.0,387,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Infilteration
434900,53,17,28/02/2018 11:32:37,903,1,1,40,139.0,40,40,...,8,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Infilteration
434901,443,6,28/02/2018 10:51:09,337504,9,8,509,3543.0,194,0,...,20,0.0,0.00000,0.0,0.0,0.000,0.000,0.0,0.0,Infilteration

In [16]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
# 2. Remove duplicate columns
df = df.loc[:, ~df.columns.duplicated()]

# 3. Remove timestamp/date columns
for col in df.columns:
    if "time" in col.lower() or "timestamp" in col.lower():
        df.drop(columns=[col], inplace=True)

# 4. Remove known duplicate CICIDS column if present
if "Fwd Header Length.1" in df.columns:
    df.drop(columns=["Fwd Header Length.1"], inplace=True)

# 5. Set target column
target_col = "Label"

# 6. Remove rows where label is missing
df = df[df[target_col].notna()]

# 7. Clean label values
df[target_col] = df[target_col].astype(str).str.strip()

# 8. Remove accidental repeated header rows
df = df[df[target_col].str.lower() != "label"]

# 9. Keep only required classes
selected_classes = [
    "Benign",
    "DDOS attack-HOIC",
    "DoS attacks-Hulk",
    "Bot",
    "FTP-BruteForce",
    "SSH-Bruteforce",
    "Infilteration",
    "DoS attacks-SlowHTTPTest",
    "DoS attacks-GoldenEye",
    "DoS attacks-Slowloris",
    "DDOS attack-LOIC-UDP",
    "Brute Force -Web",
    "Brute Force -XSS",
    "SQL Injection"
]
df = df[df[target_col].isin(selected_classes)]

# 10. Replace infinity values
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# 11. Convert feature columns to numeric
for col in df.columns:
    if col != target_col:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# 12. Remove null values
df.dropna(inplace=True)

# 13. Remove duplicate rows
df.drop_duplicates(inplace=True)

# 14. Encode labels
label_encoder = LabelEncoder()
df["Encoded_Label"] = label_encoder.fit_transform(df[target_col])

# 15. Separate features and target
X = df.drop(columns=[target_col, "Encoded_Label"])
y = df["Encoded_Label"]

# 16. Keep only numeric features
X = X.select_dtypes(include=[np.number])

# 17. Remove low-information sparse rows
non_zero_mask = (X != 0).sum(axis=1) > 5
X = X[non_zero_mask]
y = y[non_zero_mask]

# 18. Final cleaned dataframe
df_cleaned = X.copy()
df_cleaned["Encoded_Label"] = y.values

# Final checks
print("Final Shape:", df_cleaned.shape)
print("\nClass Encoding:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nClass Distribution:")
print(df_cleaned["Encoded_Label"].value_counts())

print("\nNull Values:", df_cleaned.isnull().sum().sum())
print("Infinity Values:", np.isinf(df_cleaned.select_dtypes(include=[np.number])).sum().sum())
print("Duplicate Rows:", df_cleaned.duplicated().sum())

Final Shape: (361333, 79)

Class Encoding:
{'Benign': np.int64(0), 'Bot': np.int64(1), 'Brute Force -Web': np.int64(2), 'Brute Force -XSS': np.int64(3), 'DDOS attack-HOIC': np.int64(4), 'DDOS attack-LOIC-UDP': np.int64(5), 'DoS attacks-GoldenEye': np.int64(6), 'DoS attacks-Hulk': np.int64(7), 'DoS attacks-SlowHTTPTest': np.int64(8), 'DoS attacks-Slowloris': np.int64(9), 'FTP-BruteForce': np.int64(10), 'Infilteration': np.int64(11), 'SQL Injection': np.int64(12), 'SSH-Bruteforce': np.int64(13)}

Class Distribution:
Encoded_Label
0     296723
4      22376
7      17934
11      8240
1       8189
13      4943
6       2174
9        538
5         90
8         42
10        38
2         31
3         11
12         4
Name: count, dtype: int64

Null Values: 0
Infinity Values: 0
Duplicate Rows: 0

In [18]:
df.shape

(361333, 80)

In [19]:
from ctgan import CTGAN
print("CTGAN installed successfully")

CTGAN installed successfully

In [21]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
from torchvision.datasets import MNIST
from torchvision import transforms
from torch.utils.data import DataLoader
import torch.optim as optim 

import matplotlib.pyplot as plt
from torchvision import transforms

In [22]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [23]:
device

device(type='cuda')

In [24]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder

target_col = "Label"
label_encoder = LabelEncoder()
df["Encoded_Label"] = label_encoder.fit_transform(df[target_col])

print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

{'Benign': np.int64(0), 'Bot': np.int64(1), 'Brute Force -Web': np.int64(2), 'Brute Force -XSS': np.int64(3), 'DDOS attack-HOIC': np.int64(4), 'DDOS attack-LOIC-UDP': np.int64(5), 'DoS attacks-GoldenEye': np.int64(6), 'DoS attacks-Hulk': np.int64(7), 'DoS attacks-SlowHTTPTest': np.int64(8), 'DoS attacks-Slowloris': np.int64(9), 'FTP-BruteForce': np.int64(10), 'Infilteration': np.int64(11), 'SQL Injection': np.int64(12), 'SSH-Bruteforce': np.int64(13)}

In [25]:
target_col = "Encoded_Label"

df_selected = X.copy()
df_selected[target_col] = y

print(df_selected.shape)
print(df_selected[target_col].value_counts())

(361333, 79)
Encoded_Label
0     296723
4      22376
7      17934
11      8240
1       8189
13      4943
6       2174
9        538
5         90
8         42
10        38
2         31
3         11
12         4
Name: count, dtype: int64

In [26]:
print("Before GAN Distribution:")
print(df_selected["Encoded_Label"].value_counts())

Before GAN Distribution:
Encoded_Label
0     296723
4      22376
7      17934
11      8240
1       8189
13      4943
6       2174
9        538
5         90
8         42
10        38
2         31
3         11
12         4
Name: count, dtype: int64

In [27]:
X_gan = df_selected.drop(columns=[target_col])
y_gan = df_selected[target_col].astype(int)

In [28]:
from sklearn.preprocessing import StandardScaler

scaler_gan = StandardScaler()

X_gan_scaled = scaler_gan.fit_transform(X_gan)

scaled_df = pd.DataFrame(
    X_gan_scaled,
    columns=X_gan.columns
)

In [29]:
import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn

X_tensor = torch.tensor(X_gan_scaled, dtype=torch.float32)
y_tensor = torch.tensor(y_gan.values, dtype=torch.long)

dataset = TensorDataset(X_tensor, y_tensor)

loader = DataLoader(
    dataset,
    batch_size=256,
    shuffle=True
)

In [30]:
input_dim = X_tensor.shape[1]

num_classes = len(np.unique(y_gan))

latent_dim = 64

print("Input Features:", input_dim)
print("Classes:", num_classes)

Input Features: 78
Classes: 14

In [32]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")
print("Torch CUDA version:", torch.version.cuda)

CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Torch CUDA version: 12.4

In [36]:
ctgan = CTGAN(
    epochs=5,
    batch_size=1024,
    verbose=True,
    enable_gpu=torch.cuda.is_available()
)

print("CTGAN CUDA setting:", ctgan._enable_gpu)

CTGAN CUDA setting: True

In [37]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.memory_allocated())
print(torch.cuda.memory_reserved())

True
0
0

In [41]:
print(ctgan._device)

cuda

In [44]:
# Convert all column names to normal string
df_ctgan.columns = df_ctgan.columns.astype(str)

# Convert dataframe string columns to object
for col in df_ctgan.columns:
    if df_ctgan[col].dtype == "string":
        df_ctgan[col] = df_ctgan[col].astype(object)

# Convert categorical columns to object/string
for col in categorical_columns:
    df_ctgan[col] = df_ctgan[col].astype(str)

print(df_ctgan.dtypes)

Dst Port           int64
Protocol           int64
Flow Duration      int64
Tot Fwd Pkts       int64
Tot Bwd Pkts       int64
                  ...
Idle Mean        float64
Idle Std         float64
Idle Max         float64
Idle Min         float64
Encoded_Label        str
Length: 79, dtype: object

In [46]:
from ctgan import CTGAN

df_ctgan.columns = df_ctgan.columns.astype(str)

for col in df_ctgan.columns:
    if df_ctgan[col].dtype == "string":
        df_ctgan[col] = df_ctgan[col].astype(object)

target_col = "Encoded_Label"

df_ctgan[target_col] = df_ctgan[target_col].astype(str)

categorical_columns = [target_col]

ctgan = CTGAN(
    epochs=50,
    batch_size=1024,
    verbose=True,
    cuda=True
)
print("start ayindhi abba pullaraoo\n")
ctgan.fit(df_ctgan, categorical_columns)
print("chee nuv waste")

C:\Users\Aditya\anaconda3\envs\dev\Lib\site-packages\ctgan\synthesizers\_utils.py:16: FutureWarning: `cuda` parameter is deprecated and will be removed in a future release. Please use `enable_gpu` instead.
  warnings.warn(

start ayindhi abba pullaraoo

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.